### ISSUE TITLE
Can this be used for other data sets of image data besides the handwritten data set

### ISSUE THREAD

**Issue by husuqi** [psanch21/VAE-GMVAE#10]

**Comment by psanch21** [comment]
Hi,

Yes, you just have to define a method in the utils file called load_XXX(). There are already two similar methods implemented: load_MNIST and load_FREY. The only thing is that you have to be careful when selecting the number of filters. If the dimensions are different from 28 pixels you may have to tweak a bit the hyperparameters.

Hope this helps!

**Comment by husuqi** [comment]
Thanks,and ,can this be used with multiple tag classification problems? such as an image containing multiple categories

**Comment by husuqi** [comment]
> Hi,
> 
> Yes, you just have to define a method in the utils file called load_XXX(). There are already two similar methods implemented: load_MNIST and load_FREY. The only thing is that you have to be careful when selecting the number of filters. If the dimensions are different from 28 pixels you may have to tweak a bit the hyperparameters.
> 
> Hope this helps!

Thanks,and ,can this be used with multiple tag classification problems? such as an image containing multiple categories
