### ISSUE TITLE
The expression of conditional prior and y-prior terms in the code.

### ISSUE THREAD

**Issue by bobxwu** [psanch21/VAE-GMVAE#2]
Hello, thanks for sharing. I've read the original paper about GMVAE. But I still don't know how to derive the conditional prior and y-prior terms as you did in the code. Can you explain more about the derivation?

**Comment by psanch21** [comment]
Hi. In Section 4 of my Bachelor's [dissertation](https://www.researchgate.net/publication/331089295_Unsupervised_Deep_Learning_Research_and_Implementation_of_Variational_Autoencoders) you may find a description of the model proposed by Nat Dilokthanakul et al. Please, notice the naming of the variables we use differs from the one of the original paper. Then, in Appendix D of the dissertation you may find the full derivation of all the terms of the ELBO. Hope this helps!

**Comment by bobxwu** [comment]
Thanks a lot for your reply. That helps much. And what is the "log det" when simplify the terms D.1 in the Appendix D?

**Comment by psanch21** [comment]
It refers to the log of the determinant of the covariance matrix (represented as sigma squared). Since we consider a mean field approximation for the distributions, the determinant of the covariance matrix is just the product of the terms in the diagonal. Hope this helps!
