### ISSUE TITLE
KL in Y prior in thesis 4.4.4

### ISSUE THREAD

**Issue by LittleYuer** [psanch21/VAE-GMVAE#6]
Hi psanch21,

Thanks for sharing the code and your thesis. 

As we know KL(A||B) is not equal to KL(B||A), May I ask why the KL equation in 4.4.4 assume they are equal.

Thanks for help.

Best, 
Yuer

**Comment by fangguo1** [comment]
Same question here, I do not understand this part either.

**Comment by psanch21** [comment]
Hi LittleYuer, fangguo1

You are totally right, thanks for opening the issue. The updated version of the code its already available and working. The updated section 4.4.4. looks like this

<img width="544" alt="Screenshot 2020-03-06 at 10 35 42" src="https://user-images.githubusercontent.com/16980895/76072138-b9cad680-5f97-11ea-9414-758da4d3e80b.png">


I hope this helps! Please let me know if you have any other question/concern

Thank you!

Pablo
