### ISSUE TITLE
How to get the ACC of clustering？

### ISSUE THREAD

**Issue by yttshj** [psanch21/VAE-GMVAE#7]
Hi psanch21,

Thanks for sharing the code and your thesis.

As we know the paper “Deep Unsupervised Clustering with Gaussian Mixture Variational Autoencoders” provides the ACC of clustering in MNIST dataset , and I wanna to get the ACC in the code ,but I could nou find it. 
Could you modify the code in "GMVAE_main.py" in order to calculate ACC？
Thanks for help.

Best,
Wishes

**Comment by psanch21** [comment]
Hi yttshj,

Thanks for your message.  Indeed, the ACC measure it's not implemented. However, if someone implements it and would like to share it, I would be happy to include it in the master branch.

Best,

Pablo
